In [13]:
import numpy as np
my_array = np.array([0,1,2,3,4])

my_list = [0,1,2,3,4]

print(my_array)
print(my_list)

print(type(my_array))
print(type(my_list))


[0 1 2 3 4]
[0, 1, 2, 3, 4]
<class 'numpy.ndarray'>
<class 'list'>


In [14]:
print(my_array + 1)
#print(my_list + 1)

print(my_list + my_list)
print(my_array + my_array)

print(my_array - my_list)

[1 2 3 4 5]
[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]
[0 2 4 6 8]
[0 0 0 0 0]


In [15]:
print(my_list * 2)

print(my_array * 2)

print(my_array / 2)

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]
[0 2 4 6 8]
[0.  0.5 1.  1.5 2. ]


In [23]:
tupla = (0,1,2,3,4)

print(tupla[2])

tupla2 = ("python", 3.9 , True, [1,2,3])
print(tupla2[3])
print(tupla)
print(tupla2)

2
[1, 2, 3]
(0, 1, 2, 3, 4)
('python', 3.9, True, [1, 2, 3])


In [24]:
dicionario = {"nome": "tiago",
              "idade": 20,
              "cidade": "belo horizonte"
}

print(dicionario)
print(dicionario["idade"])
dicionario["idade"] = 30
print(dicionario["idade"])


{'nome': 'tiago', 'idade': 20, 'cidade': 'belo horizonte'}
20
30
