In [29]:
lista = [10,20,30,40,50]
lista[2] = 60

lista .append(70)

lista .pop(0)

lista . sort()

print("crescente:" ,lista)
lista .sort(reverse=True)
print ("decrescente:" ,lista)

soma = sum(lista)
media = soma / len(lista)
print(f"soma e {soma} com media {media}")





crescente: [20, 40, 50, 60, 70]
decrescente: [70, 60, 50, 40, 20]
soma e 240 com media 48.0


In [1]:
tupla = ("carlos","tiago", "eder","valmir")
print(tupla[1])

tiago


In [7]:
clientes = ("carlos","tiago", "eder","valmir")

clientes = list(clientes)

clientes[1] = "marcos"

clientes = tuple(clientes)
print(nova_tupla)

('carlos', 'marcos', 'eder', 'valmir')


In [10]:
clientes = ("carlos","tiago", "eder","valmir")

cliente = input()

if cliente in clientes:
    print(f"{cliente} está na lista clientes!")
else:
    print(f"{cliente} não está na clientes!")

carlos está na lista clientes!


In [13]:
clientes = ("carlo","jose")
cliente = ("valmir", "vinicius")
print(clientes + cliente)

('carlo', 'jose', 'valmir', 'vinicius')


In [19]:
clientes = ("carlo","jose")
print(clientes .index("carlo"))



0


In [37]:
import numpy as np
array = np .array([10,20,30,40])
print(array + 2)

[12 22 32 42]


In [38]:
print(array * 3)

[ 30  60  90 120]


In [39]:
print(array + array)

[20 40 60 80]


In [40]:
print((array + array) / 2)
print("media:", np.mean(array))
print("desvio padrao:", np.std(array))

[10. 20. 30. 40.]
media: 25.0
desvio padrao: 11.180339887498949


In [41]:
print(array[array % 2 == 0])

[10 20 30 40]


In [52]:
compras ={
    "carne": 50,
    "frango": 30,
    "arroz": 30
}

print(compras["carne"])

50


In [53]:
compras["tomate"] = 10
compras["carne"] = 60
print(compras)

{'carne': 60, 'frango': 30, 'arroz': 30, 'tomate': 10}


Percorra o dicionário e exiba cada chave e valor. 

In [54]:
del compras["tomate"]
print(compras)

{'carne': 60, 'frango': 30, 'arroz': 30}


In [55]:
for chaves, valor in compras .items():
    print(f"prudutos:{compras}, preco:{valor}")

prudutos:{'carne': 60, 'frango': 30, 'arroz': 30}, preco:60
prudutos:{'carne': 60, 'frango': 30, 'arroz': 30}, preco:30
prudutos:{'carne': 60, 'frango': 30, 'arroz': 30}, preco:30


In [56]:
lista_tuplas = list(compras .items())
print(lista_tuplas)

[('carne', 60), ('frango', 30), ('arroz', 30)]
